services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443/tcp"
    env_file:
      - ./.env
    environment:
      TZ: "${TIMEZONE:-Asia/Tokyo}"
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.rule: "Host(`${DASHBOARD_HOSTNAME}`)" # Hostname for this dashboard
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.tls.certresolver: cloudflare
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - traefik:/letsencrypt
    extra_hosts:  
      - "host.docker.internal:host-gateway"
  traefik-ssl-certificate-exporter:
    container_name: traefik-cert
    image: rafi0101/traefik-ssl-certificate-exporter:latest
    environment:
      CRON_TIME: "* * * * *"
      CERT_OWNER_ID: "0"
      CERT_GROUP_ID: "1000"
    volumes:
      - traefik:/app/traefik/
      - traefik-certs:/app/certs
    restart: unless-stopped

networks:
  default:
    name: traefik-nw
    external: true

volumes:
  traefik:
    name: traefik
  traefik-certs:
    name: traefik-certs
